"""Repository-split, license-filtered real documents with incremental global dedup."""
from __future__ import annotations
import argparse, collections, hashlib, json, os, re, sqlite3, time
from pathlib import Path
from urllib.parse import urlparse
import pyarrow.parquet as pq

ROOT=Path('data/research_v1'); RESULTS=Path('results/research_v1')
LICENSES={'mit':'MIT','apache-2.0':'Apache-2.0','bsd-2-clause':'BSD-2-Clause','bsd-3-clause':'BSD-3-Clause','isc':'ISC','cc0-1.0':'CC0-1.0','unlicense':'Unlicense'}
LANGUAGES={'GO':'Go','Shell':'Bash','HTML':'HTML/CSS','CSS':'HTML/CSS'}
EXTENSIONS={'.py':'Python','.js':'JavaScript','.ts':'TypeScript','.tsx':'TypeScript','.c':'C','.h':'C',
            '.cpp':'C++','.hpp':'C++','.cc':'C++','.hh':'C++','.c++':'C++','.h++':'C++','.rs':'Rust',
            '.java':'Java','.cs':'C#','.go':'Go','.sql':'SQL','.sh':'Bash','.bash':'Bash','.zsh':'Bash',
            '.html':'HTML/CSS','.css':'HTML/CSS','.md':'Markdown','.markdown':'Markdown',
            '.rb':'Ruby','.php':'PHP','.lua':'Lua','.pl':'Perl','.scala':'Scala','.jl':'Julia',
            '.hs':'Haskell','.asm':'Assembly','.f90':'FORTRAN','.f':'FORTRAN','.tex':'TeX',
            '.ps1':'PowerShell','.psd1':'PowerShell','.bat':'Batchfile','.cmd':'Batchfile','.vb':'Visual Basic',
            '.cmake':'CMake','.dockerfile':'Dockerfile'}
BENCHMARK=re.compile(r'human.?eval|\bmbpp\b|bigcodebench|leetcode|codewars|project.?euler',re.I)
def digest(text):return hashlib.sha256(text.encode('utf-8')).hexdigest()
def normalized(text):return text.replace('\r\n','\n').replace('\r','\n').rstrip()
def split(group,seed=42,fraction=.03):return 'val' if int(digest(str(seed)+'\0'+group)[:16],16)/2**64<fraction else 'train'
def candidate(row,source,row_index):
    code='codeparrot' in source['dataset'];text=row.get('content',row.get('code','')) if code else row.get('text','')
    if not isinstance(text,str) or not 128<=len(text.encode('utf-8'))<=200000:return None,'size'
    if '\x00' in text or text.count('\ufffd')/len(text)>.001:return None,'encoding'
    if len(text.splitlines())<3 and code:return None,'single_line_or_minified'
    if max(map(len,text.splitlines()),default=0)>3000:return None,'long_line_generated'
    if BENCHMARK.search(str(row.get('repo_name',''))+'/'+str(row.get('path',''))):return None,'benchmark_repository_or_path'
    if code:
        license=LICENSES.get(str(row.get('license','')).lower())
        if not license:return None,'license'
        repo=str(row.get('repo_name','')).strip();path=str(row.get('path','')).strip()
        if not repo or not path:return None,'missing_repository_provenance'
        if re.search(r'(^|/)(node_modules|vendor|third_party|third-party|dist|build|\.git)/',path,re.I):return None,'vendored_or_generated_path'
        if re.search(r'auto.?generated|do not edit|generated by',text[:1000],re.I):return None,'generated_header'
        if re.search(r'GNU (?:GENERAL|LESSER|AFFERO) PUBLIC LICENSE',text[:3000],re.I):return None,'conflicting_license_header'
        inferred=EXTENSIONS.get(Path(path).suffix.lower(),{'Makefile':'Makefile','Dockerfile':'Dockerfile'}.get(Path(path).name,'unknown'))
        language=LANGUAGES.get(row.get('language'),row.get('language',inferred))
        if language=='unknown':return None,'language'
        kind='technical' if language=='Markdown' else 'context' if int(digest(text)[:8],16)%10==0 else 'code'
        if kind=='technical' and not re.search(r'install|documentation|function|api\b|program|usage|configuration|library|package|build',text,re.I):return None,'nontechnical_markdown'
        group='github:'+repo.lower()
        display=f'<repo>{repo}\n<file>{path}\n'+text if kind=='context' else text
        provenance={'repository':repo,'repository_path':path,'license':license,'license_annotation':row.get('license')}
    else:
        if float(row.get('score',3))<3 or float(row.get('language_score',1))<.8:return None,'education_or_language_score'
        url=str(row.get('url',''));host=(urlparse(url).hostname or '').lower().removeprefix('www.')
        if not host:return None,'missing_url'
        kind='general';language='English';group='web:'+host;display=text
        provenance={'license':'ODC-By-1.0 (collection)','document_license':'not independently annotated; CommonCrawl source terms',
                    'url':url,'source_id':row.get('id'),'crawl':row.get('dump'),'crawl_date':row.get('date'),'crawl_file':row.get('file_path'),'education_score':row.get('score')}
    return dict(text=display,source_content_sha256=digest(text),sha256=digest(display),normalized_sha256=digest(normalized(text)),
                split=split(group),split_group=group,kind=kind,language=language,
                source=source['dataset'],revision=source['revision'],source_file=source['remote_file'],row_index=row_index,**provenance),None

def ingest():
    directory=ROOT/'documents';directory.mkdir(parents=True,exist_ok=True)
    db=sqlite3.connect(ROOT/'dedup.sqlite');db.execute('CREATE TABLE IF NOT EXISTS docs (hash TEXT PRIMARY KEY, normalized TEXT UNIQUE, split TEXT, group_id TEXT)')
    state_path=RESULTS/'ingestion_state.json';state=json.loads(state_path.read_text()) if state_path.exists() else {'files':{},'counts':{},'document_bytes':{}}
    counts=collections.Counter(state['counts']);sizes=collections.Counter(state['document_bytes'])
    # Candidate reservoir byte budgets are intentionally larger than final token quotas.
    budgets={'code':900_000_000,'technical':240_000_000,'general':300_000_000,'context':130_000_000}
    handles={(s,k):(directory/f'{s}_{k}.jsonl').open('a',encoding='utf-8') for s in ('train','val') for k in budgets}
    try:
        plan=json.loads((RESULTS/'source_plan.json').read_text())
        for source in plan['files']:
            p=Path(source['local_path']);key=source['dataset']+'/'+source['remote_file']
            if not p.exists() or state['files'].get(key,{}).get('complete'):continue
            parquet=pq.ParquetFile(p);row_index=0
            # Committed per-source progress makes ordinary restarts append only new rows.
            skip=state['files'].get(key,{}).get('rows',0)
            for batch in parquet.iter_batches(batch_size=2048):
                for row in batch.to_pylist():
                    index=row_index;row_index+=1
                    if index<skip:continue
                    counts['raw']+=1;doc,rejection=candidate(row,source,index)
                    if rejection:counts['rejected/'+rejection]+=1;continue
                    kind=doc['kind'];split_=doc['split'];bucket=f'{split_}/{kind}'
                    n=len(doc['text'].encode('utf-8'))
                    if sizes[bucket]>=budgets[kind]*(1 if split_=='train' else .05):counts['rejected/reservoir_full']+=1;continue
                    try:db.execute('INSERT INTO docs VALUES(?,?,?,?)',(doc['source_content_sha256'],doc['normalized_sha256'],split_,doc['split_group']))
                    except sqlite3.IntegrityError:counts['duplicates']+=1;continue
                    handles[split_,kind].write(json.dumps(doc,ensure_ascii=False)+'\n');sizes[bucket]+=n
                    counts['accepted']+=1;counts['docs/'+bucket]+=1;counts['language/'+doc['language']]+=1;counts['license/'+doc['license']]+=1
                for f in handles.values():f.flush()
                db.commit();state['files'][key]={'rows':row_index,'complete':False};state.update(counts=dict(counts),document_bytes=dict(sizes));state_path.write_text(json.dumps(state,indent=2))
            state['files'][key]={'rows':row_index,'complete':True};state_path.write_text(json.dumps(state,indent=2))
            print(json.dumps({'file':key,'rows':row_index,'counts':dict(counts),'bytes':dict(sizes)}),flush=True)
    finally:
        for f in handles.values():f.close()
        db.close()
    return state
if __name__=='__main__':
    lock=ROOT/'ingestion.lock'
    fd=os.open(lock,os.O_CREAT|os.O_EXCL|os.O_WRONLY)
    try:
        os.write(fd,str(os.getpid()).encode());os.close(fd);ingest()
    finally:lock.unlink(missing_ok=True)
